usr/include/*/qt5/QtWebEngine/*/QtWebEngine/
usr/include/*/qt5/QtWebEngineCore/*/QtWebEngineCore/
usr/include/*/qt5/QtWebEngineWidgets/*/QtWebEngineWidgets/
usr/lib/*/qt5/mkspecs/modules/qt_lib_webengine_private.pri
usr/lib/*/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri
usr/lib/*/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri
usr/lib/*/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri
